name: devbox
services:

  devbox:
    image: devbox:latest
    restart: always
    ports:
      - "2222:22"
    networks:
      - devbox
    volumes:
      - devbox:/home/workspace

volumes:
  devbox:
    external: true

networks:
  devbox:
    external: true